apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero-system
spec:
  template:
    spec:
      containers:
      - name: local-volume-provider
        ports:
        - containerPort: 3000
          name: fileserver
          protocol: TCP
