apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero-system

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 11.3.1
    releaseName: velero
    namespace: velero-system
    valuesFile: helm-values.yaml

resources:
  - scc-rbac.yaml
  - backupstoragelocation.yaml
  - schedule-hourly.yaml
  - schedule-daily.yaml

patchesStrategicMerge:
  - service-patch.yaml
  - deployment-patch.yaml
