apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-backup-storage
  namespace: velero-system
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  selector:
    matchLabels:
      type: nfs
      app: velero
  volumeName: velero-backup-storage
