apiVersion: v1
kind: PersistentVolume
metadata:
  name: velero-backup-storage
  labels:
    type: nfs
    app: velero
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - hard
    - intr
  nfs:
    server: qnap-01.rh-lab.morey.tech
    path: /storage-mass/ocp-home/velero
