apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup
  namespace: velero-system
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "20"
spec:
  schedule: "0 * * * *"
  template:
    ttl: 168h0m0s
    storageLocation: nfs
    labelSelector:
      matchLabels:
        backup.velero.io/schedule: hourly
    snapshotVolumes: true
