apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "20"
spec:
  schedule: "0 2 * * *"
  template:
    ttl: 168h0m0s
    storageLocation: nfs
    includedNamespaces: []
    labelSelector:
      matchLabels:
        backup.velero.io/schedule: daily
    snapshotVolumes: true
