apiVersion: v1
kind: Service
metadata:
  name: velero
  namespace: velero-system
spec:
  ports:
    - name: http-monitoring
      port: 8085
      targetPort: http-monitoring
    - name: local-volume-api
      port: 3000
      targetPort: 3000
