# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   name: rhcl-operator-group
# spec:
#   targetNamespaces:
#     - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
spec:
  name: rhcl-operator
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: rhcl-operator-1.3.0
