apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvm-nvme1n1
  annotations:
    # CRD might not be installed yet during initial Argo CD sync.
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    deviceClasses:
      - deviceSelector:
          paths:
            - /dev/nvme1n1
          forceWipeDevicesAndDestroyAllData: true
        fstype: xfs
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
          sizePercent: 90
          name: thin-pool
          overprovisionRatio: 10
        name: lvm-nvme1n1-vg
        default: true
