apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/morey-tech/gitops-catalog/openshift-pipelines-operator/overlays/pipelines-1.20?ref=openshift-pipelines-1.20

# openshift-pipelines