apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mongodb-kubernetes-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: mongodb-kubernetes-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mongodb-kubernetes-operator.v1.6.1
