apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-storage-mass
  labels:
    type: nfs
    app: paperless
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - hard
    - intr
  nfs:
    server: 192.168.6.20
    path: /storage-mass/ocp-home/paperless
