apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage-mass
  labels:
    app: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: paperless-storage-mass
  storageClassName: ""
