apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-devspaces
resources:
  - checluster.yaml
  - github-oauth.yaml
  - claude-code-api-key.yaml
  - roo-code-settings-template.yaml
  - roo-code-generate-script.yaml
  - roo-code-vscode-config.yaml
