apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets-system
resources:
  - bitwarden-cli-deploy.yaml
  # - bitwarden-secret.yaml
  - secret-stores.yaml

helmCharts:
- name: external-secrets
  includeCRDs: true
  version: 1.3.2
  repo: https://charts.external-secrets.io
  releaseName: external-secrets
  namespace: external-secrets-system
  valuesInline:
    global:
      compatibility:
        openshift:
          # Use built-in OpenShift support instead of patch to remove runAsUser
          adaptSecurityContext: force
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

images:
  - name: ghcr.io/morey-tech/bitwarden-cli
    newTag: 2025.12.1

