kind: Deployment
apiVersion: apps/v1
metadata:
  name: ccpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccpt
  template:
    metadata:
      labels:
        app: ccpt
    spec:
      volumes:
        - name: ccpt-db
          persistentVolumeClaim:
            claimName: ccpt-db
        - name: ccpt-config
          configMap:
            name: ccpt-config
      containers:
        - resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ccpt
          env:
            - name: DATABASE_PATH
              value: /app/data/credit_cards.db
            - name: CONFIG_PATH
              value: /app/config/config.yaml
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: ccpt-db
              mountPath: /app/data/
            - name: ccpt-config
              mountPath: /app/config/
          image: 'ghcr.io/morey-tech/credit-card-payment-tracker:latest'
      restartPolicy: Always
