---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-uid-3001-binding
  namespace: uid-gid-in-action
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:allowed-uid-3001
subjects:
  - kind: ServiceAccount
    name: allowed-uid-3001-sa
    namespace: uid-gid-in-action
