---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocked-uid-2001-deploy
  labels:
    app: blocked-uid-2001-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocked-uid-2001-test
  template:
    metadata:
      labels:
        app: blocked-uid-2001-test
    spec:
      serviceAccountName: allowed-uid-3001-sa
      securityContext:
        runAsUser: 2001
        runAsGroup: 2001
      volumes:
        - name: nfs-batch-job-file-storage
          persistentVolumeClaim:
            claimName: nfs-batch-job-file-storage
      containers:
        - name: podcool
          image: quay.io/wcaban/podcool
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs-batch-job-file-storage
              mountPath: "/mnt/nfs/share"
          resources: {}
