apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-sa-deploy
  labels:
    app: default-sa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-sa-test
  template:
    metadata:
      labels:
        app: default-sa-test
    spec:
      securityContext:
        runAsUser: 4001
      volumes:
        - name: nfs-batch-job-file-storage
          persistentVolumeClaim:
            claimName: nfs-batch-job-file-storage
      containers:
        - name: podcool
          image: quay.io/wcaban/podcool
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs-batch-job-file-storage
              mountPath: "/mnt/nfs/share"
          resources: {}
