apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
 labels:
   app: myapp
spec:
 replicas: 3
 selector:
   matchLabels:
     app: myapp
 template:
   metadata:
     labels:
       app: myapp
   spec:
     containers:
     - name: podcool
       image: quay.io/wcaban/podcool
       ports:
       - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: toolbox
 labels:
   app: toolbox
spec:
 replicas: 3
 selector:
   matchLabels:
     app: toolbox
 template:
   metadata:
     labels:
       app: toolbox
   spec:
     containers:
     - name: net-toolbox
       image: quay.io/wcaban/net-toolbox
       ports:
       - containerPort: 2000
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: toolbox2
 labels:
   app: toolbox2
spec:
 replicas: 3
 selector:
   matchLabels:
     app: toolbox2
 template:
   metadata:
     labels:
       app: toolbox2
   spec:
     securityContext:
       supplementalGroups: [1000930001]
       seLinuxOptions:
        level: s0:c31,c0
     containers:
     - name: net-toolbox
       image: quay.io/wcaban/net-toolbox
       ports:
       - containerPort: 2000
       securityContext:
           runAsUser: 1000930001