---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: must-run-as-3001-deploy
  labels:
    app: must-run-as-3001-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: must-run-as-3001-test
  template:
    metadata:
      labels:
        app: must-run-as-3001-test
    spec:
      serviceAccountName: must-run-as-3001-sa
      securityContext:
        supplementalGroups:
          - 2001
      volumes:
        - name: nfs-batch-job-file-storage
          persistentVolumeClaim:
            claimName: nfs-batch-job-file-storage
      containers:
        - name: podcool
          image: quay.io/wcaban/podcool
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs-batch-job-file-storage
              mountPath: "/mnt/nfs/share"
          resources: {}
