---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-batch-job-file-storage
  labels:
    name: nfs-batch-job-file-storage
spec:
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nfs/share
    server: nfs.lab.morey.tech
  persistentVolumeReclaimPolicy: Retain