apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplemental-groups-deploy
  labels:
    app: display-results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: display-results
  template:
    metadata:
      labels:
        app: display-results
    spec:
      securityContext:
        fsGroup: 2001
        supplementalGroups:
          - 2001
      volumes:
        - name: nfs-batch-job-file-storage
          persistentVolumeClaim:
            claimName: nfs-batch-job-file-storage
      containers:
        - name: podcool
          image: quay.io/wcaban/podcool
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs-batch-job-file-storage
              mountPath: "/mnt/nfs/share"
          resources: {}
