apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: models
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
      serviceAccountName: default
      initContainers:
        - name: download-model
          image: registry.redhat.io/ubi8/python-312:latest
          command:
            - /bin/bash
            - '-c'
          args:
            - |-
              echo "Install hf CLI with PIP"
              pip install -U "huggingface_hub==1.1.4"
              echo -----------------------------------

              echo "Downloading Model: $MODEL_REPO / $MODEL_FILE"
              hf download $MODEL_REPO $MODEL_FILE --local-dir=/models
              echo -----------------------------------
          env:
            - name: MODEL_REPO
              valueFrom:
                configMapKeyRef:
                  name: model-download-config
                  key: MODEL_REPO
            - name: MODEL_FILE
              valueFrom:
                configMapKeyRef:
                  name: model-download-config
                  key: MODEL_FILE
          volumeMounts:
            - name: model-volume
              mountPath: /models
          workingDir: /workspace/model
      containers:
        - name: inference-server
          image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9:latest'
          imagePullPolicy: IfNotPresent
          env:
            - name: VLLM_SERVER_DEV_MODE
              value: '1'
            - name: MODEL_FILE
              valueFrom:
                configMapKeyRef:
                  name: model-download-config
                  key: MODEL_FILE
            - name: SERVED_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: model-download-config
                  key: SERVED_MODEL_NAME
          command:
            - /bin/bash
            - '-c'
          args:
            - |-
              python -m vllm.entrypoints.openai.api_server \
                --port=8000 \
                --model=/model/$MODEL_FILE \
                --served-model-name=$SERVED_MODEL_NAME \
                --tensor-parallel-size=1 \
                --max-model-len=25990 \
                --dtype=auto \
                --gpu-memory-utilization=0.90
          resources:
            limits:
              cpu: '10'
              nvidia.com/gpu: '1'
              memory: 12Gi
            requests:
              cpu: '1'
              memory: 6Gi
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: model-volume
              mountPath: /model
            - name: shm
              mountPath: /dev/shm 
      restartPolicy: Always