kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: interence-server
spec:
  to:
    kind: Service
    name: inference-server
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
