resources:
  - model-storage.yaml
  - model-download-task.yaml
  - model-download-pipeline.yaml
  # - inference-server-deploy.yaml
  # - inference-server-route.yaml
  # - inference-server-service.yaml