resources:
  # - inference-server-deploy.yaml
  # - inference-server-route.yaml
  # - inference-server-svc.yaml
  - model-download-pipeline.yaml
  - model-download-pvc.yaml
  - model-download-task.yaml