kind: Service
apiVersion: v1
metadata:
  labels:
    metrics: workload-monitor
  name: inference-server
spec:
  ports:
    - name: inference-server
      protocol: TCP
      port: 80
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: inference-server
