pve_api_host: ms-02.home.morey.tech
pve_api_user: ansible@pve
pve_api_token_id: ansible
pve_api_token_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34393032353138346537316564346663373631306131386630623439383636636134353362633466
          3961643738666165666262646634393232363835333038330a663662376434383836643261313362
          30373230643562636164393332363830643136356435613736636332383336613332663963323363
          3530333361646233610a326363643564663464656361356238646532653534306239343064633061
          38303563653333366334376331323534643836346536663532613362343830356532383662383464
          6364333330663063636366613439396130623461656433386364

# https://console.redhat.com/openshift/token
# TODO: ocm login --use-device-code
rh_console_offline_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30306633396264616665303239653465363063666336366363653334386138393032376565626535
          3732646530626533323766323962633362666162363762360a346138613932396436356239643161
          65623630356233323864343133366538366363356237613830653333306636633631353736346239
          3166303437626236630a306134303435333166343033613766656334366364666535336663313961
          32356135373763386566646339343863633733316332343735303663656133323962646538653864
          33363139373165306264633035303165643937356331646162306131326264373636366133613637
          63643935336164313761373634383133373131653165313164663764363137396231663930336663
          31613939353534653636303463373762336638386130373165383430303666633637376132663033
          38613438303461636334333632646461646230653166653961663931323763626332383135393566
          65386430356466373731633364306663613334643363333066656538373766316638363433353363
          33663861613962383063383162643935383863656465613966333536656263353232366438666333
          30663966653732323062386435393330636335333432333833396436663266656339356337323735
          39336264316438353730396536656330383063646166653666343732386661633561363235653337
          31643765616139336439653266343736373634363262316233323434366661363662613732643039
          38303964623363653664303565313965353763633365363863613763373261353132373534616666
          64326566643532633265303937323263363634333066653633653565636461613836353937323165
          34663333643634376364613631613731643431623439333035326534353533393834303361366636
          35616134393466316562613564316665333831626333663338633032333265633332376136356365
          31396331346333313338646234333739376133386335646264616337633163626263663637333738
          38303238346132303865636565613161613036623539386639636336313834623162363062376334
          30326562666333343431383865346239323962336635363864326330303564373331333362353134
          30326536343666363130633330663130613130633939646133396131343030343034343938373833
          66663838376439656264346238663362336133303161663932346239353364386638633739316362
          39623238356462346634353662373139613837353835333762333939333662303632316262616133
          65613138313833353530383962366135306334643839356135383262313535313261626134643733
          62363132353232333738303739326135633538343466316234633866666434383233373438333337
          62653965346561636331656636373536386466646266316631653630343335373964643931666138
          38333435373663333466333864376563666363346630323765396339376237376663326362366437
          34323730313062396366306331666462623666653163393033643664636165636338316232393962
          62343734353130343162303734346236396235643535353163623962373930613063653463626531
          38323939383932333566366635613037633063316263346432623162356564656537343038383766
          63393933393461653361633138353138626562326532636163656533396565326461393634623132
          38333463373266303938646138323966326265313666666135643939383638363138653936353562
          63303566643031323962623437333039656464366230343134383333363138633838363631353137
          66353130373632386130343332633436663665396236643031303664633332336136326536343562
          64313464333131636232303330633166316132356634313733346163343365623533323034336634
          39383463396261363933653762366137306363323430373134353131373139643163633335636135
          34666266303632313335356265373031656636343331633230393436616632613265376334613761
          62313361396464643062663764353562383965336666643339623138356238356265613762393831
          63353066366666376339643930366263346338613434323439376365616631353230626538333837
          33306361363934373666373563393934323634343964383261356336353435653766336664383935
          64626332616536303135616639323330626461653136396633373738323063306332666338383738
          35383632666133663563303338326330376435313564663064656232303832373864393831363034
          37656362666230393765

rh_console_pull_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63613630306331626134303762386237656438376531666437316564643132336539306434393036
          3635323261326365393335396334386165353134613430610a633264626336316134626564386130
          65663439333334383364343833336438646561656439386234646531336565356662393737333065
          6435663736313031650a333738616662626331633832646139643763643963343431376664376231
          61613936373233363636666162333239343638386234373165656531303066383335373136323839
          37633635303630313535373035373361336163383832356166303230333238663238343436383631
          32373265393463353566383863353039616436356562623264663037656364626231666262636665
          65393835623935393834623234643864663165636530313938616364653437336135343731393038
          35383464663032633637616531356336326462353232323263383036666238373535346162313566
          63326336336164316563333930303639613866396533363465376431666631626464626331613432
          30343239336634623234623030633838323239383339333139653264663364653439613061653864
          38323536353166326562653232356134313839303831333035653730393439623930326539633663
          61373435623432343435643530386265366361316366366666336364646166353464616336646635
          33623534346665316365383564613065343934636630633762353565393665633133363331316332
          31653438626637343339373038396465316563396334356235336438373835393361376537633664
          33343635646136616531393237376133346662626636633437306431616162663833653335363161
          65383037333731306164663033373137346233636662323566333638396335306661343962666236
          33376133323661383266316561633934333131646261326638326133663263613033373565323165
          35333930616466656664613266646536346136653735393732346132656437643030623034616530
          37356137393537353863333634366663646635343135636261353436656630616661343461343039
          65656266353566333839373663616239333833396363633035383632626134366666313561383432
          31383934666633346432333033346334393964356533646566353737343637363932306163373066
          61613730383737393234323665643066323566643063623465326332643864646430356261333839
          66306464313235353432383964613234376535383161313262376339313738323064613164353637
          37616637323938663962663865653462393530613364323638623439656430623934323432383566
          63636633306137303461313137363633303664613630326137323639343961343139663236386131
          30643737373236306236343732663165656434353166613630633435333261623331646131633864
          32626637353332393038616537386435343235343931646230653230623537303537653363363432
          65656137663732313638643831306666666265353639333638333437336134383431616534383262
          32656665313234663138643230336663643237383265373661306561386665323039316236336166
          33356533373534393464646537313361666634323166646138323134306331393730613830313438
          39363832323261333233333435343738356433663731653639356133336564353162666563383561
          33333566633330393635393532326637323731353136616234666330323863316430626564306634
          36653333373365303937343532313636383961613837653132313362383163633632633661313733
          35623535643130353437363831363330656636643433653737323264336538643235386137376439
          39326339613130303633353232633833313830616465623330613234626335646666663331333663
          65393437306265356338613564643538333265383032353730623632636334393162613135373736
          38633538363639383630613536353865653439393935306261386565363761633233666332633663
          38303665623765386230303330316435336463396463646463383937396432316436653163343430
          37323563336638616361316630613261343532643035346332326363653764323232616336613933
          30323662626434393938343536393964383933313931633931333437386139646563343633306631
          63636331366532643739386132633737346336336535326637316530346362613537323861623539
          31393964346238663330363133343564353237633731396165646662323861363437333865343238
          65346634626661303430336233646130303131623766306335633432643062656239393963336238
          37396165366532653731333936326339353062656633363861633137396335316163396437373963
          61386139303935343463316230626463613366393331333061303531303461326166626338636461
          66663762633838346363623237666237616361396461333964633534613335373730653936636337
          32333432626131376238326335323338343662376436643565316636356532346337363765346236
          63316236366237313730343436306437373930303964383938323063323764303362373730633936
          62623734663466656531653931313566646432346333373035663565656130303434313332376436
          34376137613131373931316364643638666233626162663566343137386433316537386461633530
          61643037313162356236666262643461633035383836666232373539316334333266396132396363
          61356665313831353063373438643233393034366630623939333636663339656361336230303530
          37646235366430633936326266346136303963343762336466636233666466356362313732343464
          33363539663935336263303334616163643637643462626331363463643365363639393131636330
          35363762343636663235356233663733326536323165396534646262626163303262623931653633
          61623636363261363666343534326133663961663961363866393035373961393135373431613562
          37626166616536346332616132306362646339333761316365303538376333393934613566303366
          38663632663434613665373436366435653734363761326433376630323763353163333135363961
          62663332613234336534633938643633393034633533316466623035343037323137383763383564
          61366266643935343933653363653265363634363333353665303963343463336537386332633830
          34656235306136356131366238623565393764303462386635356339323935376236323032363363
          64613836306138663061333035666235643336343132663236306636613665326539353463353564
          64373863356132616138366333316138316530353561613464313331343936626437376631373532
          38643230353939313463303938336634646165613633323235386631306265613838653236316435
          36363030343535303734653366346166633764356539323635346232613331393633663330326630
          37613335653333386533663537303436633561376530333364396235383232656565346637346535
          33646461646361383433383638656437633764363661623734333330613665336336633537616536
          66613832626364346536326637326366346430303063333735626636623538663736653065353863
          62636137353233646138393236616261323831323935613836393438316134643431636666646631
          35376433303236613234356666353932643465616462636135303664646566653632633366303037
          33333230306336313133333636316466396362363633323063643861666533623635313263633138
          64613766353036613164393830376639306236626263663262643938363830393265663732303265
          63653735363161386530396362653338313837333939386563323863313632613464643838643337
          33643934303466303334333265336263623062666339373935383865313863303037373564376436
          32633461663035656466363065633062333931653332383038353761663036633564633963636539
          61393265383963653433313232343231353633366561626430343064636464646439343666623264
          64383964633033313330303838653335636631633164316362646339366232333132353264633530
          65613839663834643562306634613461373434356362613565643865363738316438663931313031
          35636533353336666163376666383732656233363434653735366365343462363237623832396637
          62343430313134346662333966353532636233656639393064663433383435363765616265313366
          33343464633430326234633733666164386638313336353164616235306630303638386139623233
          34316237333964363636303633646537653731363364353332356434353133396238616261366235
          30366138613463383035313061306638626665373336383666333130663662653861393237393939
          34613561303833326435316634616236353335306334356261333361313965626266613230313063
          37633438666435396566363837343965316364366336313138373639336632343065313233323335
          38393139616166383937386562333561333466383338333730316430346238613436306464343136
          36306663383566616239646235626537363330636234316337336435343136373662346235376130
          63643433396261343334393034643333653438613831626165663537376330353239613532343866
          35353331623632346266326463313633613632306530363033386136373031393463383565343131
          61373361333364653036633939663135306130343035613231373134336232323066326639646632
          63373431353738663731303933633136643230343666353763306131353830396133663930633964
          63343863383539373039396632623330353933316334343736363366303132646333633135376164
          31303831343338393961343631306339636365376565353661356565313437363365623437663639
          32303062383330363636373539353039343862323235356161656535353564393731383161336163
          39623962626131656565383466323363653630343831666131323439366339333564356461613932
          65643131343164323630386239623335396264616239363435656165333832613264323336633438
          37353732663737386264633138623661313763666161316665646535656438326665343739376263
          36626361653435633238303034353239323366306436373031343562643936653665393563323863
          64396231376262323038366335386534616439306664643536313563393662333465616438356437
          65666135663962633132633631353535313464653264306635386561663961616138643562316336
          32343065333362643966656266336136646161353036383633386336663034663339343964306333
          30626338326261396362336634336666633230316664656237626665393665386434633233313564
          38383830616261323666373532303539346231653138663531316661343331643139396632656338
          31373233666633386232323935343533616134376636643232626563643764313933636237393463
          62663761616339336234303035653539663562653532643264353834616636333438306235636231
          65613135373335636533636131383637333033313861313962646330633230636364333466623332
          32636331326361303464303337336230313033353963643734656330653933376330616330633164
          32363938613566346234383732616436386233623664373634303538336461393633646664356565
          35633035633436366235643237643637656436373935656364633537303837383538373039303330
          63623237333632646362656236666431383665313238653565336235303461663735373362616564
          32316466376462643862613161663437303963653835386435653036623637373039323165663839
          30306264613638613132626439626662303165663732616432336338373962653035643061363139
          39636661396465646339303363346138636239616532313337396165663762313432613136653537
          62656537616261376236323730346261376361613563373235646633306466323233656665383530
          34636133343033393436373361633662303734343931373766643461666535636162333039383733
          36393735623239363130623335666335383663383035663138346461353138313065666138383838
          30306561346562376430656133396239643763656332333833303265373637363334653332663535
          39653136316531363530373039393938666538363436373934373464333964616439356363613164
          63623134356139356331373435613261306263303035633537346463356234393962303230656366
          63373835383036393361646365636235643430343132396166353035393233613631336134633466
          37376239633263313439636133326135346663356463383865373731623432313066393665373061
          34396530643234393435316630383534313136346235353333383662613536373435623762356130
          62613066373233643638343933333863336236383363353336323832333138313738306164333136
          66303166656665633635343333316631633630383961393038616664653635323831303336373061
          36653539323232363533626262616363303631636437623164393136373764613363346536396663
          61636130366439666565656235393966623764303735643634376532393366646338656565363933
          34333333633966383464663334383232346562613535343863616333396334663131303433613962
          62363661373663643333333735343564333431623638346438333561613434653533663138363835
          31656563316163313661633038386431663263373666333937383735633930653766666166653664
          64373734343263613235633536353236633665353831643232653834356438306464313133396637
          66363031343633666264303862663032646565663631326664323139306430366263366432366435
          61333234616337343331333666313566663132336239613461393039393066643466313636396139
          61383938616631303561373130323239373931636662323737306534353765333130636334393363
          61353065353036363438323239663933313065616464396465356664386666616430636263393465
          34396261643434343336303732616432356331643135313532646564376230373730663032633832
          61396534633139383531643362313565316437383836616163303835633337303434626134336531
          63623939363634366262303665326538313839616131643730363031396364613165663463623466
          31636565613930663066646330366138663738386363623062376161316238396362353737396533
          32336537333131643632633032323933376130666438663662623932373938343566353737323632
          62393166343937363861363332393038383232633038613637383065623965613639323533343432
          35383632633133626433323330633463366564373266653864383932623032613130306162313439
          62376336386533316537376132623936663166613163363062376563653566313732316634373464
          38363738653264353731616265626666396339643433313637356239336464383032333332376132
          30343430343666653063656132356332623133303434396433343663303965363963633263363564
          38326434623563656637333464353863303063326232333737363263623263613865623430366235
          38633432306166333036653636646539623437396638636132636462623836313133326534643465
          38663834623432326466353833346464656632383063646231616236386138333961626165336637
          32343866376161666238363631336539363731396461366232303038366334353839363566643430
          32393730373365623037656364303364366666353137393761376630623064666632383031333835
          63633230336563303835356661356466306135323666363936303563633637653436353732636532
          37616231653565326561323563303061303239663061343964346632633730313764383032326634
          6234
