# FerretDB - Open source MongoDB alternative
# Provides MongoDB wire protocol (port 27017) backed by PostgreSQL
# Used as a drop-in replacement for MongoDB to support UniFi Network Application
# https://www.ferretdb.com/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.1.0
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: 'postgresql://unifi@unifi-postgres-rw.unifi.svc.cluster.local:5432/unifi'
---
apiVersion: v1
kind: Service
metadata:
  name: ferretdb
  namespace: unifi
spec:
  selector:
    app: ferretdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
