apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-postgres-password
spec:
  target:
    name: unifi-postgres-password
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: unifi
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 05fa2ea9-7ef0-4ffd-aae5-b3bb000a9937
        property: password
