kind: Deployment
apiVersion: apps/v1
metadata:
  name: anythingllm
  labels:
    app: anythingllm
    app.kubernetes.io/component: anythingllm
    app.kubernetes.io/instance: anythingllm
    app.kubernetes.io/name: anythingllm
    app.kubernetes.io/part-of: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
        deployment: anythingllm
    spec:
      containers:
      - name: anythingllm
        image: 'quay.io/rh-aiservices-bu/anythingllm-workbench:1.9.1'
        ports:
          - containerPort: 8888
            protocol: TCP
        envFrom:
          - secretRef:
              name: inference-server-config
        volumeMounts:
          - name: storage
            mountPath: /app/server/storage
        resources: {}
