apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: apps-wildcard-cert
  namespace: openshift-ingress
spec:
  isCA: false
  commonName: "apps.ocp-mgmt.rh-lab.morey.tech" 
  secretName: apps-wildcard-cert 
  dnsNames:
  - "apps.ocp-mgmt.rh-lab.morey.tech" 
  - "*.apps.ocp-mgmt.rh-lab.morey.tech" 
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer