apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-storage-mass-library
  labels:
    type: nfs
    app: immich
spec:
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - hard
    - intr
  nfs:
    server: 192.168.6.20
    path: /storage-mass/ocp-home/immich/library
