apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-storage-mass
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: immich-data-storage-mass
  storageClassName: ""
