apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oadp-backup-storage
  namespace: openshift-adp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  selector:
    matchLabels:
      type: nfs
      app: oadp
  volumeName: oadp-backup-storage
