apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 2 * * *"
  template:
    ttl: 168h0m0s
    storageLocation: velero-1
    includedNamespaces: []
    labelSelector:
      matchLabels:
        backup.velero.io/schedule: daily
    defaultVolumesToFsBackup: true
    snapshotMoveData: false
