apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 * * * *"
  template:
    ttl: 168h0m0s
    storageLocation: velero-1
    includedNamespaces:
      - backup-test
    defaultVolumesToFsBackup: true
    snapshotMoveData: false
