apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 1-operator.yaml
  - 2-credentials-secret.yaml
  - 2-nfs-pv.yaml
  - 2-nfs-pvc.yaml
  - 3-dataprotectionapplication.yaml
  - 4-backupstoragelocation.yaml
  - 5-schedule-hourly.yaml
  - 5-schedule-daily.yaml
