kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ccpt
spec:
  host: ccpt.apps.ocp-home.rh-lab.morey.tech
  path: /
  to:
    kind: Service
    name: ccpt
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
