apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/gpu-operator-certified/operator/overlays/v25.3?ref=main
  - nfd-instance.yaml