kind: Service
apiVersion: v1
metadata:
  name: anythingllm-vllm-cpu
  labels:
    app: anythingllm-vllm-cpu
    app.kubernetes.io/component: anythingllm
    app.kubernetes.io/instance: vllm-cpu
    app.kubernetes.io/name: anythingllm
    app.kubernetes.io/part-of: anythingllm
    backend: vllm-cpu
spec:
  ports:
    - name: 8888-tcp
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: anythingllm-vllm-cpu
    deployment: anythingllm-vllm-cpu
