apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: aap-terraform-state
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: aap-terraform-state
  objectBucketName: obc-aap-aap-terraform-state
  storageClassName: openshift-storage.noobaa.io