kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wingspan-scoring-db
  labels:
    backup.velero.io/schedule: hourly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: lvms-lvm-nvme1n1-vg
  volumeMode: Filesystem
