---
collections:
  - name: community.general
    version: "12.2.0"
  # Proxmox modules moved from community.general in v11.0.0
  - name: community.proxmox
    version: "1.1.0"
  # rhpds.assisted_installer
  - name: git+https://github.com/rhpds/assisted_installer
    version: v0.0.2
  - name: pfsensible.core
    version: "0.7.1"
  # pfsensible.haproxy fork with TCP/SNI support
  - name: git+https://github.com/morey-tech/pfsensible-haproxy.git
    version: 0.2.0
