---
collections:
  - name: community.general
    version: "10.7.7"
  # rhpds.assisted_installer
  - name: git+https://github.com/rhpds/assisted_installer
    version: v0.0.2
  - name: pfsensible.core
    version: "0.6.2"
  # pfsensible.haproxy fork with TCP/SNI support
  - name: git+https://github.com/morey-tech/pfsensible-haproxy.git
    version: 0.2.0
