apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-auth
spec:
  target:
    name: cloudflare-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_API_TOKEN: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 43124cf1-7da0-4a8f-a308-b121010e5d08
        property: password
