---
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.8/html/operators/understanding-operators#olm-operatorgroups-membership_olm-understanding-operatorgroups
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap-operator-group
spec:
  # List of namespaces to watch for operator-managed resources (i.e. AnsibleAutomationPlatform CRs).
  targetNamespaces:
    - openshift-aap
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aap-subscription
spec:
  channel: 'stable-2.5'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Dummy secret to prevent harmless error events.
# https://github.com/ansible/awx-operator/issues/922
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkdW1teS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6ImR1bW15IiwicGFzc3dvcmQiOiJkdW1teSIsImF1dGgiOiJaSFZ0YlhrNlpIVnRiWGs9In19fQ==
kind: Secret
metadata:
  name: redhat-operators-pull-secret
type: kubernetes.io/dockerconfigjson