apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox

patches:
  - target:
      kind: PersistentVolumeClaim
      name: valkey-data-netbox-valkey-primary-0
    patch: |-
      - op: add
        path: /metadata/labels/backup.velero.io~1schedule
        value: hourly
  - target:
      kind: PersistentVolumeClaim
      name: valkey-data-netbox-valkey-replicas-0
    patch: |-
      - op: add
        path: /metadata/labels/backup.velero.io~1schedule
        value: hourly

# # Add the route for NetBox.
# resources:
#   - route.yaml

# # Use the NetBox Helm chart for deployment.
# helmCharts:
# - includeCRDs: true
#   name: netbox
#   namespace: netbox
#   releaseName: netbox
#   repo: https://charts.netbox.oss.netboxlabs.com/
#   version: 6.0.59

# patches:
# # These patches use separate files to fix the security
# # context for the NetBox StatefulSet and Deployment in OpenShift.
# # - path: statefulset-scc-fix.yaml
# #   target:
# #     group: apps
# #     kind: StatefulSet
# #     version: v1
# - path: deployment-scc-fix.yaml
#   target:
#     group: apps
#     kind: Deployment
#     version: v1