apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-homelab-private
spec:
  target:
    name: github-homelab-private
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        githubAppID: |-
          {{ .appID }}
        githubAppInstallationID: |-
          {{ .installID }}
        githubAppPrivateKey: |-
          {{ .privateKey }}
        type: git
        url: https://github.com/morey-tech/homelab-private.git
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
  - secretKey: appID
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: e6827b60-eddf-4081-b6e5-b1270013b87c
      property: app-id
  - secretKey: installID
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: e6827b60-eddf-4081-b6e5-b1270013b87c
      property: install-id
  - secretKey: privateKey
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: e6827b60-eddf-4081-b6e5-b1270013b87c
      property: private-key-base64
      decodingStrategy: Base64
  