apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-appset
spec:
  goTemplate: true
  syncPolicy:
    applicationsSync: create-update
  generators:
  - git:
      repoURL: https://github.com/morey-tech/homelab.git
      revision: HEAD
      directories:
      - path: kubernetes/ocp-home/system/*
  ignoreApplicationDifferences:
    - jsonPointers:
      # Allow automated sync policy to be disabled manually.
      - /spec/syncPolicy/automated
      # Allow target revision to be set manually for PR testing,
      - /spec/source/targetRevision
  template:
    metadata:
      name: '{{.path.basename}}-system'
    spec:
      project: default
      source:
        repoURL: https://github.com/morey-tech/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}-system'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - allowEmpty=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            openshift.io/cluster-monitoring: "true"
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
  templatePatch: |
    {{- if eq .path.basename "openshift-cnv" }}
    spec:
      destination:
        namespace: openshift-cnv
    {{ end }}
    {{- if eq .path.basename "openshift-operators" }}
    spec:
      destination:
        namespace: openshift-operators
    {{ end }}
    {{- if eq .path.basename "openshift-devspaces" }}
    spec:
      destination:
        namespace: openshift-devspaces
    {{ end }}
    {{- if eq .path.basename "openshift-nfd" }}
    spec:
      destination:
        namespace: openshift-nfd
    {{ end }}
